server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sign_up_login
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update